### ISSUE TITLE
Plans to release training code?

### ISSUE THREAD

**Issue by jasonlee-sf** [OS-Copilot/OS-Atlas#12]
Hi,

Congrats on the great work. Any plans to release the training code? Will be hugely appreciated.

**Comment by LividWo** [comment]
Yes. But it will take a while since our code is heavily based on our company's infra.

**Comment by CarlHuangNuc** [comment]
期望尽快release 训练脚本，，

**Comment by CarlHuangNuc** [comment]
依然没有release 训练脚本
