### ISSUE TITLE
OSworld test code

### ISSUE THREAD

**Issue by CarlHuangNuc** [OS-Copilot/OS-Atlas#18]
Hi Authors,

     Is there a plan to publicly release the osworld test script code for this great job?

**Comment by CarlHuangNuc** [comment]
依然没有看到这部分代码呀，，，

**Comment by xyzhang626** [comment]
hey @Ananwang2002 any updates on this?

**Comment by jayabrata97** [comment]
Hi @Ananwang2002, Is there any update on this?
