### ISSUE TITLE
Whether IG data will public in future ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [OS-Copilot/OS-Atlas#20]
![image](https://github.com/user-attachments/assets/182d8354-d159-4e3e-84d0-45a6fdc948f1)

**Comment by LividWo** [comment]
Yes. Keep an eye on https://huggingface.co/datasets/OS-Copilot/OS-Atlas-data

**Comment by CarlHuangNuc** [comment]
依然等待大佬开源这部分数据，，

**Comment by CarlHuangNuc** [comment]
这部分json 文件没有release
