### ISSUE TITLE
Where can I find the data synthesis toolkit?

### ISSUE THREAD

**Issue by QunixZ** [OS-Copilot/OS-Atlas#24]
Denoting in your parer that "We have developed and released the first multi-platform GUI grounding data synthesis toolkit"
But I don know where it is, it's very kind of you if someone could tell me.
Thank you for your excellent work & dataset.

**Comment by LividWo** [comment]
We are working on the cleaning and rebasing of our toolkit for open sourcing.

**Comment by efeiefei** [comment]
Hello，how is the progress of the synthesis tool?

**Comment by hhxxttxsh** [comment]
+1 Could you please share any details on windows desktop data collection?
