### ISSUE TITLE
训练数据集格式

### ISSUE THREAD

**Issue by zhoumenghan** [OS-Copilot/OS-Atlas#27]
您好，非常感谢您的工作！
我按照您在https://huggingface.co/datasets/OS-Copilot/OS-Atlas-data中给出的数据格式（如:细节1）处理了数据，sft训练qwen2-vl-7b，小训了1000step，之后用与OS-ATLAS相同的prompt测试模型效果，但我发现，输出格式不太一样（如图2），想问一下，我这个训练数据格式是否正确，还是说应该改为以下训练数据格式（如图3）呢？非常期待您的解答，感谢~

细节1:
[
  {
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nUsing the provided screenshot, I'll describe webpage elements for you to locate (with bbox).\n**<ref>System</ref>\n<ref>Save to Google Drive</ref>\n<ref>More options menu</ref>\n<ref>Learn more about results and reviews \"Helix Fruit Jump Arcade Game\"</ref>\n<ref>See more personalized recommendations</ref>"**
      },
      {
        "from": "gpt",
        **"value": "<ref>System</ref><box>[[951, 0, 1000, 18]]</box>\n<ref>Save to Google Drive</ref><box>[[514, 288, 555, 361]]</box>\n<ref>More options menu</ref><box>[[910, 87, 926, 115]]</box>\n<ref>Learn more about results and reviews \"Helix Fruit Jump Arcade Game\"</ref><box>[[708, 810, 713, 827]]</box>\n<ref>See more personalized recommendations</ref><box>[[739, 626, 773, 660]]</box>"**
      }
    ],
    "images": [
      "/home/test2/LAM/OS-Atlas-data/desktop_domain/linux_desktop/output_20240912_152854_original_screenshot.png"
    ]
  },.......

细节2：
![image](https://github.com/user-attachments/assets/393005b2-ca8e-4197-a01f-8f2c4da0645b)

细节3：
[
  {
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nUsing the provided screenshot, I'll describe webpage elements for you to locate (with bbox).\n**<|object_ref_start|>System<|object_ref_end|>\n<|object_ref_start|>Save to Google Drive<|object_ref_end|>\n<|object_ref_start|>More options menu<|object_ref_end|>\n<|object_ref_start|>Learn more about results and reviews \"Helix Fruit Jump Arcade Game\"<|object_ref_end|>\n<|object_ref_start|>See more personalized recommendations<|object_ref_end|>"**
      },
      {
        "from": "gpt",
        **"value": "<|object_ref_start|>System<|object_ref_end|><|box_start|>(951, 0), (1000, 18)<|box_end|>\n<|object_ref_start|>Save to Google Drive<|object_ref_end|><|box_start|>(514, 288), (555, 361)<|box_end|>\n<|object_ref_start|>More options menu<|object_ref_end|><|box_start|>(910, 87), (926, 115)<|box_end|>\n<|object_ref_start|>Learn more about results and reviews \"Helix Fruit Jump Arcade Game\"<|object_ref_end|><|box_start|>(708, 810), (713, 827)<|box_end|>\n<|object_ref_start|>See more personalized recommendations<|object_ref_end|><|box_start|>(739, 626), (773, 660)<|box_end|>"**
      }
    ],
    "images": [
      "/home/test2/LAM/OS-Atlas-data/desktop_domain/linux_desktop/output_20240912_152854_original_screenshot.png"
    ]
  },

**Comment by numbmelon** [comment]
`<ref>System</ref><box>[[951, 0, 1000, 18]]</box>` 是InternVL的训练格式，qwen2vl的训练格式参考你图中/细节3中给出的altas-7b的输出即可。

**Comment by zhoumenghan** [comment]
感谢回复~
