### ISSUE TITLE
关于prompt.json

### ISSUE THREAD

**Issue by zhoumenghan** [OS-Copilot/OS-Atlas#28]
请问prompt.json在训练grounding模型阶段有用到吗，感觉prompt.json里面的内容似乎跟“In this UI screenshot, what is the position of the element corresponding to the command \"{instruction}\" (with bbox)?"没啥太大关系，我自己训练（用的是qwen2-vl正确的训练格式，仅训练了1000step）并用
        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": f"{img_path}",
                    },
                    {"type": "text",
                     "text": f"In this UI screenshot, what is the position of the element corresponding to the command \"{instruction}\" (with bbox)?"},
                ],
            }
        ]
测试的模型效果的时候，output千奇百怪，如下：
举例1   ['The element corresponding to the command "click the button to create a new project" is located at the position (852, 92), with a bounding box of (852, 92, 981, 132).<|im_end|>']

举例2   ['The element corresponding to the command "view my account profile" is located at the top right corner of the UI screenshot. The bounding box (bbox) for this element is:\n\n- Top-left corner: (916, 16)\n- Bottom-right corner: (964, 44)\n\nThis is the element with the profile icon (a circle with a face) next to the number 20.<|im_end|>']

我看OS-ATLAS-base-7b的输出非常规整，基本保持如下格式：
["<|object_ref_start|>input volume's slider<|object_ref_end|><|box_start|>(738,766),(904,792)<|box_end|><|im_end|>"]   
["<|object_ref_start|>output volume's slider<|object_ref_end|><|box_start|>(736,388),(902,410)<|box_end|><|im_end|>"] 
['<|object_ref_start|>显示器分辨率的下拉菜单<|object_ref_end|><|box_start|>(834,685),(971,731)<|box_end|><|im_end|>']

想问一下，出现以上情况是因为我训练的step太少吗，是在训练初期的正常情况吗，是否有其他设定保证了输出格式，此问题困扰我两天，非常希望您能指出问题所在，感谢您~

**Comment by zhoumenghan** [comment]
是不是由于我这1000step大致分布在了desktop数据上，我刚才用desktop数据测试了一下，输出是：
 ['<|object_ref_start|>close this window<|object_ref_end|><|box_start|>(959, 141), (981, 182)<|box_end|><|im_end|>']
看着正常

**Comment by zhoumenghan** [comment]
又用desktop数据多测了测，结果有规整的，也有不规整的，如下，您觉得是否是因为训练step太少导致的？
['The element corresponding to the command "check bluetooth" is located at the position (540, 195) with a bounding box of (540, 195) to (608, 250).<|im_end|>']
 ['The element corresponding to the command "check the date and time" is located in the top right corner of the screenshot. The bounding box (bbox) for this element is:\n\n- Top: 0\n- Left: 720\n- Height: 50\n- Width: 100<|im_end|>']
 ['The element corresponding to the command "connect wifi" is located in the top menu bar of the UI screenshot. The bounding box (bbox) for this element is:\n\n- Top-left corner: (470, 0)\n- Bottom-right corner: (529, 64)\n\nThis means the element is positioned from the 470th pixel from the left edge of the screen to the 529th pixel, and from the 0th pixel from the top edge of the screen to the 64th pixel from the top edge of the screen.<|im_end|>']
 ['The "zoom in" command is located at the bottom right corner of the UI screenshot. The bounding box (bbox) for this element is:\n\n```plaintext\n(878, 939), (921, 972)\n```<|im_end|>']
 ['The element corresponding to the command "switch to device" is located at the top left corner of the UI screenshot. The bounding box (bbox) for this element is:\n\n```\n(100, 46), (200, 83)\n```<|im_end|>']

**Comment by numbmelon** [comment]
我觉得应该是模型在特定格式上欠拟合了，可以加大一下训练量试试。如果暂时只想用少量数据的话可以调整一下learning rate和epoch

**Comment by zhoumenghan** [comment]
好的，非常感谢~
