### ISSUE TITLE
action fine-tuning model

### ISSUE THREAD

**Issue by aptsunny** [OS-Copilot/OS-Atlas#7]
It seems that the OS-Atlas model for action fine-tuning has not been released yet. Is there any plan to open source this part?

**Comment by jasonlee-sf** [comment]
+1. Two models that were released https://huggingface.co/OS-Copilot/OS-Atlas-Base-7B only seem to be doing grounding rn.

**Comment by LividWo** [comment]
The pro version of action models are released now, check it out https://huggingface.co/OS-Copilot/OS-Atlas-Pro-7B
